events {}
http {
    server {
        listen 3100;
        
        location /loki/api/v1/push {
            if ($http_authorization != "Bearer SuperSecretToken2026") {
                return 401 "Unauthorized: Invalid or Missing Bearer Token";
            }
            proxy_pass http://loki:3100;
        }
    }
}
